defaults: &defaults
  some_setting: "asdf"
  ssedap_location: "http://ssedap.dev"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  ssedap_location: "https://ssedap"

